name: Deploy to Production
 
on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
      
jobs:          
  request-production-deployment:
    name: Request Production Deployment
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get last commit message
      id: last_commit
      run: |
        msg=$(git log -1 --pretty=format:"%h - %s (%an)")
        echo "message=$msg" >> $GITHUB_OUTPUT
        
    - name: Create Deployment Request
      run: echo "Deployment to production server needs approval ."
 
    - name: Wait for Approval
      uses: trstringer/manual-approval@v1
      timeout-minutes: 2

      with:
        secret: ${{ github.TOKEN }}
        approvers: mazibinfo
        minimum-approvals: 1
        issue-title: "Deploying to production from staging."
        issue-body: |
          Please approve or deny the deployment.

          **Last Commit:**
          ${{ steps.last_commit.outputs.message }}
        exclude-workflow-initiator-as-approver: false
  
  hello-world-job:
    name: Print Hello world
    runs-on: ubuntu-latest
    needs: request-production-deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Hello World
      run: echo "Hello, World!"

  # deploy-to-production:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: request-production-deployment
 
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
 
  #   - name: Deploy to Production Server
  #     uses: appleboy/ssh-action@master

  #     with:
  #       host: ${{ secrets.PROD_HOST }}
  #       username: ${{ secrets.PROD_USERNAME }}
  #       password: ${{ secrets.PROD_PASSWORD }}

  #       script: |
  #           set -e # Exit immediately if a command fails
  #           export NVM_DIR=~/.nvm
  #           source ~/.nvm/nvm.sh
  #           cd /var/www/mediusware-com-v2
  #           git reset --hard || { echo "Git reset failed"; exit 1; }
  #           git fetch origin || { echo "Git fetch failed"; exit 1; }
  #           git reset --hard origin/production || { echo "Git pull failed"; exit 1; }
  #           npm install || { echo "npm install failed"; exit 1; }
  #           npm run build || { echo "Build failed"; exit 1; }
  #           supervisorctl restart mediusware.com

# steps:
#   - uses: trstringer/manual-approval@v1
#     with:
#       secret: ${{ github.TOKEN }}
#       approvers: user1,user2,org-team1
#       minimum-approvals: 1
#       issue-title: "Deploying v1.3.5 to prod from staging"
#       issue-body: "Please approve or deny the deployment of version v1.3.5."
#       exclude-workflow-initiator-as-approver: false
#       fail-on-denial: true
      # additional-approved-words: ''
      # additional-denied-words: ''
